### ISSUE TITLE
Live Chord Verifier

### ISSUE THREAD

**Issue by joseph-vedadi** [ayushkumarshah/Guitar-Chords-recognition#3]
Very nice job done. 

I think it would be fantastic :
if It could recognize and verify the guitar chord played, for practicing.. . 
For example, when I am practicing to learn how to play guitar, I run the software, Set it to "E major" and play and look for green Light ...

**Comment by ayushkumarshah** [comment]
Thank you very much @joseph-vedadi . I really appreciate your feedback. I have recently updated the repository with detailed instructions and maintainability of the packages. You might want to check it out. Also, regarding the feature you have suggested, I will definitely try to add it when I have time. Thank you.

**Comment by joseph-vedadi** [comment]
Very very nice. 
I am very interested to understand how you did it. 
Could you be kind enough to meet online to go over :
how you designed it?
and why you designed it as such .. 
 (google-Hangout, Whatsup .. )

Once again .. very nice job
